# Site settings
# in the templates available like {{ site.myvariable }}.
title: Hải Dương Audio
email: haiduong2623@gmail.com
brand: HDAudioVN
headline: Chuyên bán thiết bị âm thanh
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://HDAudioVN.github.io" # the base hostname & protocol for your site
copyright: 2019 Hải Dương Audio. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: haiduong2623@gmail.com
phone: +84 522 628 887

# Tracking
googleAnalitycsID: UA-83933844-1

